# Generated by Django 4.2.3 on 2023-07-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=20)),
                ('adhar_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('passport_number', models.CharField(max_length=20)),
            ],
        ),
    ]
