# Generated by Django 4.2.3 on 2023-07-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_rename_adhar_number_candidate_adharnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='pan_number',
            new_name='pannumber',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='passport_number',
            new_name='passportnumber',
        ),
    ]
