# Generated by Django 4.2.3 on 2023-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_rename_pan_number_candidate_pannumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='adharnumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pannumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passportnumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
